//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brainer.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameSession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GameSession()
        {
            this.GameSessionDetails = new HashSet<GameSessionDetails>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public System.Guid GameId { get; set; }
        public Nullable<System.Guid> LevelId { get; set; }
        public Nullable<decimal> AverageThinkingTime { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Game Game { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameSessionDetails> GameSessionDetails { get; set; }
    }
}
