//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brainer.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameSessionDetails
    {
        public System.Guid Id { get; set; }
        public System.Guid GameSessionId { get; set; }
        public Nullable<bool> AnswerValue { get; set; }
        public Nullable<decimal> AnswerTime { get; set; }
    
        public virtual GameSession GameSession { get; set; }
    }
}
