//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brainer.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level
    {
        public System.Guid Id { get; set; }
        public int UserId { get; set; }
        public System.Guid GameId { get; set; }
        public int Value { get; set; }
        public int BonusesPlayed { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
