//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brainer.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetails
    {
        public System.Guid Id { get; set; }
        public int UserId { get; set; }
        public int RoleId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool Gender { get; set; }
        public Nullable<int> DayOfBirth { get; set; }
        public Nullable<int> MonthOfBirth { get; set; }
        public Nullable<int> YearOfBirth { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual webpages_Roles webpages_Roles { get; set; }
    }
}
